"use node";

import { action } from "./_generated/server";
import { v } from "convex/values";

export const generate = action({
  args: { projectId: v.id("projects"), companyId: v.id("companies") },
  handler: async (ctx, args) => {
    const a = (await import("./_generated/api")).api as any;

    // Gather today's activity
    const project = await ctx.runQuery(a.projects.getById, { id: args.projectId });
    if (!project) throw new Error("Project not found");

    const now = new Date();
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();

    // Field notes from today
    const allNotes = await ctx.runQuery(a.fieldNotes.list, { projectId: args.projectId });
    const todayNotes = (allNotes || []).filter((n: any) => n.createdAt >= todayStart);

    // Documents uploaded today
    const allDocs = await ctx.runQuery(a.docManager.list, { companyId: args.companyId, projectId: args.projectId as string });
    const todayDocs = (allDocs || []).filter((d: any) => {
      if (!d.uploadedAt) return false;
      return new Date(d.uploadedAt).getTime() >= todayStart;
    });

    // Communications from today
    const allEmails = await ctx.runQuery(a.emails.list, { companyId: args.companyId as string });
    const todayEmails = (allEmails || []).filter((e: any) => {
      if (e.projectId !== args.projectId) return false;
      if (e.createdAt && e.createdAt >= todayStart) return true;
      if (e.date) return e.date === now.toISOString().slice(0, 10);
      return false;
    });

    // Build summary
    const dateStr = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });

    let summary = `# Daily Project Summary\n`;
    summary += `**${project.name}**${project.code ? ` (${project.code})` : ""}\n`;
    summary += `${dateStr}\n\n`;

    if (todayNotes.length > 0) {
      summary += `## 📝 Field Notes (${todayNotes.length})\n`;
      todayNotes.forEach((n: any) => {
        const time = new Date(n.createdAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
        summary += `- **${time}** — ${n.note} *(${n.author || "Unknown"})*\n`;
      });
      summary += "\n";
    }

    if (todayDocs.length > 0) {
      summary += `## 📄 Documents Uploaded (${todayDocs.length})\n`;
      todayDocs.forEach((d: any) => {
        summary += `- ${d.name} (${d.category || "Uncategorized"})${d.uploadedBy ? ` — uploaded by ${d.uploadedBy}` : ""}\n`;
      });
      summary += "\n";
    }

    if (todayEmails.length > 0) {
      summary += `## 💬 Communications (${todayEmails.length})\n`;
      todayEmails.forEach((e: any) => {
        summary += `- **${e.subject || "(No Subject)"}** — ${e.source || "Email"}${e.from ? ` from ${e.from}` : ""}\n`;
      });
      summary += "\n";
    }

    const totalItems = todayNotes.length + todayDocs.length + todayEmails.length;
    if (totalItems === 0) {
      summary += `*No activity recorded today. Use Field Notes, Log Call, or upload documents to track daily activity.*\n`;
    }

    summary += `\n---\n*Generated by OpsSlate at ${now.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}*\n`;

    return { summary, stats: { notes: todayNotes.length, docs: todayDocs.length, emails: todayEmails.length } };
  },
});
